name: Release
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use node 16.x
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: 16.x
      - name: Cache node_modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
          key: >-
            ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-${{
            github.sha }}
          restore-keys: |
            ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-
            ${{ runner.os }}-modules-
      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v3
        with:
          path: |
            .turbo-cache
            node_modules/.cache/turbo
          key: "${{ runner.os }}-turbo-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-turbo-
      - name: Yarn install
        run: yarn install --no-progress --non-interactive
      - name: Build Yanz UI
        run: yarn build
      - name: Build storybook
        run: yarn build-storybook
        working-directory: ./packages/storybook
      - uses: actions/upload-artifact@v2
        with:
          name: yanz-ui-storybook
          path: packages/storybook/storybook-static
          retention-days: 1
  deploy-chromatic:
    runs-on: ubuntu-latest
    needs:
      - build-storybook
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use node 18.x
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: 18.x
      - name: Cache node_modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
          key: >-
            ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-${{
            github.sha }}
          restore-keys: |
            ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-
            ${{ runner.os }}-modules-
      - name: Yarn install
        run: yarn install --no-progress --non-interactive
      - uses: actions/download-artifact@v2
        with:
          name: yanz-ui-storybook
          path: packages/storybook/storybook-static
      - name: Trigger Chromatic release
        uses: chromaui/action@v1
        if: github.ref != 'refs/heads/main'
        with:
          storybookBuildDir: storybook-static
          workingDir: packages/storybook
          token: "${{ secrets.GITHUB_TOKEN }}"
          projectToken: "${{ secrets.CHROMATIC_PROJECT_TOKEN }}"
      - name: Trigger Chromatic release (Production)
        uses: chromaui/action@v1
        if: github.ref == 'refs/heads/main'
        with:
          storybookBuildDir: storybook-static
          workingDir: packages/storybook
          token: "${{ secrets.GITHUB_TOKEN }}"
          projectToken: "${{ secrets.CHROMATIC_PROJECT_TOKEN }}"
          autoAcceptChanges: true
